In [ ]:
import sqlite3 as sql
import pandas as pd

conn = sql.connect('chinook.db')
conn 

qry = "SELECT * FROM customers"

def get_data(qry):
    df = pd.read_sql_query(qry, conn)
    return df

In [6]:
qry =  "Select * from sqlite_master"
get_data(qry)

,type,name,tbl_name,rootpage,sql
0,table,album,album,2,CREATE TABLE [album]\n(\n [album_id] INTEGE...
1,table,artist,artist,3,CREATE TABLE [artist]\n(\n [artist_id] INTE...
2,table,customer,customer,4,CREATE TABLE [customer]\n(\n [customer_id] ...
3,table,employee,employee,5,CREATE TABLE [employee]\n(\n [employee_id] ...
4,table,genre,genre,6,CREATE TABLE [genre]\n(\n [genre_id] INTEGE...
5,table,invoice,invoice,7,CREATE TABLE [invoice]\n(\n [invoice_id] IN...
6,table,invoice_line,invoice_line,8,CREATE TABLE [invoice_line]\n(\n [invoice_l...
7,table,media_type,media_type,9,CREATE TABLE [media_type]\n(\n [media_type_...
8,table,playlist,playlist,10,CREATE TABLE [playlist]\n(\n [playlist_id] ...
9,table,playlist_track,playlist_track,11,CREATE TABLE [playlist_track]\n(\n [playlis...
10,index,sqlite_autoindex_playlist_track_1,playlist_track,12,None
11,table,track,track,13,CREATE TABLE [track]\n(\n [track_id] INTEGE...
12,index,ifk_albumartist_id,album,16,CREATE INDEX [ifk_albumartist_id] ON [album] (...
13,index,ifk_customersupport_rep_id,customer,17,CREATE INDEX [ifk_customersupport_rep_id] ON [...
14,index,ifk_employeereports_to,employee,18,CREATE INDEX [ifk_employeereports_to] ON [empl...
15,index,ifk_invoicecustomer_id,invoice,19,CREATE INDEX [ifk_invoicecustomer_id] ON [invo...
16,index,ifk_invoice_lineinvoice_id,invoice_line,20,CREATE INDEX [ifk_invoice_lineinvoice_id] ON [...
17,index,ifk_invoice_linetrack_id,invoice_line,21,CREATE INDEX [ifk_invoice_linetrack_id] ON [in...
18,index,ifk_playlist_tracktrack_id,playlist_track,22,CREATE INDEX [ifk_playlist_tracktrack_id] ON [...
19,index,ifk_trackalbum_id,track,23,CREATE INDEX [ifk_trackalbum_id] ON [track] ([...
20,index,ifk_trackgenre_id,track,24,CREATE INDEX [ifk_trackgenre_id] ON [track] ([...
21,index,ifk_trackmedia_type_id,track,25,CREATE INDEX [ifk_trackmedia_type_id] ON [trac...
22,table,wishlist_track,wishlist_track,261,CREATE TABLE wishlist_track(\nwishlist_id Inte...
23,index,sqlite_autoindex_wishlist_track_1,wishlist_track,262,None
24,table,wishlist,wishlist,260,"CREATE TABLE ""wishlist"" (\n\t""whishlist_id""\tI..."
25,view,CUSTOMER_ABV2_90,CUSTOMER_ABV2_90,0,CREATE VIEW CUSTOMER_ABV2_90 as \n sele...
26,view,customer_get_90_dollars,customer_get_90_dollars,0,CREATE VIEW customer_get_90_dollars as\n Sel...
27,view,customer_usa,customer_usa,0,CREATE VIEW customer_usa as\n sele...
28,view,customer_gt_90_dollars,customer_gt_90_dollars,0,CREATE VIEW customer_gt_90_dollars as\n Sele...
29,view,city_redmond,city_redmond,0,CREATE VIEW city_redmond as\n sele...
30,view,CUSTOMER_ABV3_80,CUSTOMER_ABV3_80,0,CREATE VIEW CUSTOMER_ABV3_80 as \n sele...

In [9]:
qry = """Select il.inovice_id, t.track_id, t.name track_name, m.name media_name, il.quantity, il.unit_price
    from invoice_lines il
    inner join track t 
    on 
    il.track_id = t.track_id
    inner join media_types m
    on t.media_type_id = m.media_type_id
    where il.invoice_id = 1
 """
 get_data(qry)

IndentationError: unexpected indent (2938674486.py, line 10)

In [27]:
import pandas as pd
import numpy as np

df = pd.read_csv('hacker_news.csv')

In [28]:
df.head()

,id,title,url,num_points,num_comments,author,created_at
0,12224879,Interactive Dynamic Video,http://www.interactivedynamicvideo.com/,386,52,ne0phyte,8/4/2016 11:52
1,11964716,Florida DJs May Face Felony for April Fools' W...,http://www.thewire.com/entertainment/2013/04/f...,2,1,vezycash,6/23/2016 22:20
2,11919867,Technology ventures: From Idea to Enterprise,https://www.amazon.com/Technology-Ventures-Ent...,3,1,hswarna,6/17/2016 0:01
3,10301696,Note by Note: The Making of Steinway L1037 (2007),http://www.nytimes.com/2007/11/07/movies/07ste...,8,2,walterbell,9/30/2015 4:12
4,10482257,Title II kills investment? Comcast and other I...,http://arstechnica.com/business/2015/10/comcas...,53,22,Deinos,10/31/2015 9:48

In [29]:
import re
re.search("and","i have tow hands")

In [30]:
title = df["title"]
pattren = "[pP]ython"

count = 0 

for i in title:
    if re.search(pattren,i):
        count += 1
        print(i)

count

From Python to Lua: Why We Switched
Ubuntu 16.04 LTS to Ship Without Python 2
Create a GUI Application Using Qt and Python in Minutes
How I Solved GCHQ's Xmas Card with Python and Pycosat. (Explanation and Source)
Unikernel Power Comes to Java, Node.js, Go, and Python Apps
Developing a computational pipeline using the asyncio module in Python 3
Show HN: Minimal, modern embedded V8 for Python
Python integration for the Duktape Javascript interpreter
Python 3 on Google App Engine flexible environment now in beta
IronPython 3 (python for .net) development restarted
Cysignals: signal handling (SIGINT, SIGSEGV, ) for calling C from Python
Ask HN: Would you be interested in an embeddable, lightweight subset of Python?
A Hello World Server in Python
Microsoft shipped Python code in 1996
Moore Foundation provides grant for Contiuum's Python Numba and Dask Compilers
Integrate Python and .NET
Face Swap (C++ / Python): Meet Ted Trump, Donald Clinton and Hillary Cruz
ImportPython
Show HN: Fabulous: Print images in terminal with Python
Python 3.5 Async IO, Matmul and Unpack Features for PyPy: Only Bug Fixes Left
Scipy Lecture Notes  Learn numerics, science, and data with Python
PeachPy: Assembly Code Generation in High-Level Python
500 Lines or Less  A Python Interpreter Written in Python
Peak detection on signals in Python
PLY (Python Lex-Yacc)  To Write a Parser in Python
Visualizing relationships between Python packages
Debugging of CPython processes with gdb
Marshmallow: Simplified object serialization for Python
Pycraft: Minecraft engine in Python
Using Google's Python Client Library to Authorise Your Desktop App with OAuth2
Exhaustive list of All Python Books (Updated)
PyThalesians: Python Open Source Financial Library
Show HN: Python Crash Course
Python wats
Free 2 Player Game [Python][Angular]
Python 3.6 proposal, PEP 525: Asynchronous Generators
Hubness-aware kNN in Python
Typeshed: static types for the Python standard library
Show HN: An experimental Python to C#/Go/Ruby/JS transpiler
Python 3  Function Overloading with singledispatch
Welcome to the Python Engineering blog
Learn data science in python by taking online course
How async/await works in Python 3.5
Ubuntu Drops Python 2.7 from the Default Install in 16.04
An OpenCV-based document scanner in Python
AWS Lambda Supports Python, Versioning, Scheduled Jobs, and 5 Minute Functions
Python 3.5 and Multitasking
Show HN: Graphene  GraphQL framework for Python
Show HN: Dplython, dplyr data manipulation for python
Show HN: Automatically import or install modules when they're needed in IPython
Polar watches/sportbands Python API
Thoughts on the future of Python and graphical interfaces
Authorization for humans (Python Package)
Writing custom type systems for Python in Prolog
Introducing TrumpScript  Make Python Great Again
A fast PostgreSQL client library for Python: 3x faster than psycopg2
See Python, See Python Go, Go Python Go
Python 3 support in scientific Python projects
Why I'm not leaving Python for Go (2012)
Kickstarter for funding Micropython port to ESP8266
Show HN: I created a Python framework for fast Slack bot development
Python 3 comes to Scrapy
Show HN: Space Shooter  Retro Game Recreated Using Python
Python Data Science Handbook Supplemental Materials
Python 3 in 2016
Python: Generators, Coroutines, Native Coroutines and Async/Await
Show HN: Learn the Amazon Echo with Python
Using attrs for everything in Python
How to build and deploy a simple Facebook Messenger bot with Python and Flask
Go bridges to JavaScript and Python
Preview the Python Serverless Microframework for AWS
Keras 1.0  Python deep learning framework
PLE: Reinforcement Learning Environment in Python
Show HN: How to add jitter to a plot using Python's matplotlib and seaborn
PyBridge - Reuse your Python code in native Android applications
Python 3.6 dict becomes compact and keywords become ordered
Memspector: Inspect memory usage of Python functions
Installing TensorFlow with Python 3 on EC2 GPU Instances
Proving that Javas and Pythons sorting algorithm is broken
MicroPython 1.5 (small Python implementation for IoT, etc.)
Show HN: TeachCraft  Learning Python Through Minecraft
Show HN: A super simple webcrawler framework written in Python
Ask HN: A statically typed alternative to Python with batteries included
Book: Deep Learning with Python
Angular 2 coming to Java, Python and PHP
Legofy  Python program to make an image to look as if it was created with Legos
Using Native Python Libraries in Lambda
Python 8 will be the next major Python version
Interactive Interpreter Tab Completion in Python
Python on Pebble
Changing the Culture of Python at Facebook [video]
Ask HN: Fun and interesting Python things to do or learn?
Ask HN: How do you provide your Python dependencies in production in 2016?
Show HN: Python 3 pyGtk graphical curve and surface fitter
Show HN: Python program to clean up handwritten notes
Document Clustering with Python
Show HN: Affirm  Improved error messages for Python assert statements
A native Python IDE built for data science
Show HN: Pycraft  learn Python with Minecraft
'New' Python modules of 2015
Recreational Maths in Python
DQN for Beginners in 200 lines of python code to play Flappy Bird with Keras
Building Powerful Frameworks in Python
Show HN: Venv2docker  create a docker image from a python virtualenv
Show HN: First Release of Transcrypt Python3.5 to JavaScript Compiler
C Is Manly, Python Is for N00bs:How False Stereotypes Turn into Technical Truths
Python implementation of statistical Dependency parsing using SVM by @rj_here
Python Decorators in 12 Steps (2012)
Python 3.5.0
EasyMake  one python file instead tons of Makefile locs
Pineapple  A standalone front end to IPython for Mac
A tool to search for Python code using jQuery-like selectors
Show HN: Automated algorithm translation for Python, C++, C#, JS
Meet Connexion: Zalando's Open-Source REST Framework for Python
Visual profiler for Python
Show HN: Update your requirements.txt file with Pur in Python
Left-pad for Python (how could we have lived all this time without it?)
CPython internals: Codewalk through the Python interpreter source code (2014)
Python, Machine Learning, and Language Wars
Code that will break in Python 4
Python-like programming language interpreter written in Python
Introducing Yosai: A Security Framework for Python Applications
Py-Videocore: Python Library for GPGPU on Raspberry Pi
let in python (2014)
MicroPython, a few years on
New string formatting in Python
Ptpython  better than ipython or bpython?
Measure the Real Size of Any Python Object
Ask HN: OO book for old Python hacker?
C++ Has Become More Pythonic (2014)
Jarvis: Personal Assistant in Python
Python Internals: PyObject
An SMS Center with Python, Kannel and a GSM Modem
The Python Paradox
How I defeated an anti-tamper APK with some Python and a homemade Smali emulator
An Introduction to Mocking in Python
Writing Pythonic code pays off
Show HN: Insideout  does this new approach to Python packaging makes sense?
Comparing Python Command-Line Parsing Libraries  Argparse, Docopt, and Click
Python: Why cant we write list.len()?
An Introduction to Scientific Python (and a Bit of the Maths Behind It)
Feather: A Fast On-Disk Format for Data Frames for R and Python
From Python to Go and Back Again
How to kill yourself in Python
Why Python 3 Exists
Show HN: Stack overflow command line client added support to python 2
Python one-liner to compare two files (conditions apply)
Python vs. C/C++ in embedded systems
The origins of the class Meta idiom in python
Python is Better than Ruby
Web Service Efficiency at Instagram with Python
Crypto and SSL toolkit for python (M2Crypto)
PythonJobs.com
Wheres Susi? Airborne Orangutan Tracking with Python and React.js
Transition to Python4 won't be like Python3(we've learned our lesson)
David Beazley  Python Concurrency from the Ground Up: Live  PyCon 2015
Ask HN: How to automate Python apps deployment?
Moving Away from Python 2
Python vs. Julia Observations
Show HN: Decorating: Animated pulsed for your slow functions in Python

160

In [31]:
pattern = "[pP]ython"

boolean = title.str.contains(pattern)
boolean.sum()

np.int64(160)

In [32]:
df['title'].loc[2022]

'Show HN: CrashBreak  Reproduce exceptions as failing tests in Ruby'

In [33]:
pattern =  "[12][0-9][0-9][0-9]"
title[title.str.contains(pattern)]

3        Note by Note: The Making of Steinway L1037 (2007)
34                        The reverse job applicant (2010)
50         Ask HN: Which framework for a CRUD app in 2016?
59            2015 in review  1 year after I quit blogging
80       Apple Watch Scooped Up Over Half the Smartwatc...
                               ...
20032    Things I Wont Work With: Dioxygen Difluoride (...
20049    Study: US is an oligarchy, not a democracy (2014)
20075    Tips from a Pro: An Introduction to Microscopi...
20081                 Usenet, what have you become? (2012)
20082    Colma, Calif., Is a Town of 2.2 Square Miles, ...
Name: title, Length: 1143, dtype: object

In [34]:
re.search('.+',"Sajid  \n \trajput")

In [38]:
text = "Sajid  \n \trajput"

result = re.sub("\s+"," ",text)
result

'Sajid rajput'

In [42]:
text = "python 123"
resutl = re.sub(r"\d","",text)
resutl

'python '

In [44]:
clean_title = []

for i in title:
    clean_title.append(re.sub(r"[^a-zA-Z0-9]\s"," ",i))


clean_title

['Interactive Dynamic Video',
 'Florida DJs May Face Felony for April Fools Water Joke',
 'Technology ventures From Idea to Enterprise',
 'Note by Note The Making of Steinway L1037 (2007)',
 'Title II kills investment Comcast and other ISPs are now spending more',
 'Nuts and Bolts Business Advice',
 'Ask HN How to improve my personal website?',
 'Shims Jigs and Other Woodworking Concepts to Conquer Technical Debt',
 'That self-appendectomy',
 'Crate raises $4M seed round for its next-gen SQL database',
 'Advertising Cannot Maintain the Internet Heres the Secret Sauce Solution',
 'Coding Is Over',
 'Show HN Wio Link ESP8266 Based Web of Things Hardware Development Platform',
 'Custom Deleters for C+ Smart Pointers',
 'How often to update third party libraries?',
 'Review my AI based marketing bot',
 'Ask HN Am I the only one outraged by Twitter shutting down share counts?',
 "Ten years later did Boston's Big Dig deliver?",
 'Valid.ly Never send another OOPS message',
 'APOD LIGO detects gravity waves...',
 'Typeplate a typographic starter kit encouraging great type on the web',
 'Ask HN Aby recent changes to CSS that broke mobile?',
 'Streamroot makes video streaming cheaper thanks to peer-to-peer',
 'VMware Confirms Layoffs as It Prepares for Dell Acquisition',
 'Firmware exploit can defeat new Windows security features on Lenovo ThinkPads',
 'The Sad State of Personal Knowledgebases',
 'US Robotics Network Taps',
 'Fundraising Advice for YC Companies',
 'PSA Intel WICS broken for years with official press release do not buy',
 'Ask HN Looking for Employee #3 How do I do it?',
 'Ask HN Someone offered to buy my browser extension from me What now?',
 'Small Indiana county sends more people to prison than San Francisco',
 'Real-time GIF images',
 'Charles River Ventures Puts F*CK Trump on Their Website',
 'The reverse job applicant (2010)',
 'Bitbucket Support GitHub-style pages for repositories and teams',
 "Estonia's Tech-Savviness",
 "'The details of your involvement will be gruesome if you continue suing us",
 'Show HN Something pointless I made',
 'Self-Driving Ubers Appear in San Francisco',
 'Maru turns Android smartphones into portable PCs',
 'Text of the Trans-Pacific Partnership',
 'Apply HN CreatorsNest On-Demand Private Workspaces for Artists and Creatives',
 'Researchers have trained a machine to spot depression on Instagram',
 'A Cars Computer Can Fingerprint You in Minutes Based on How You Drive',
 'Show HN Shanhu.io a programming playground powered by e8vm',
 'The Path to Rust',
 'Bitcoin Is Back But It Never Really Left',
 'Ask HN Limiting CPU memory and I/O usage on a program for testing',
 'How to write a great error message',
 'Ask HN Which framework for a CRUD app in 2016?',
 'Entrepreneurship A second attempt  Feedback welcomed',
 'The Shocking Secret About Static Types',
 'Atom 1.6 Released with Pending Pane Items Async Git and Top and Bottom Bar API',
 'Obama on Climate Change The Trends Are Terrifying',
 'When there are too many administrators which ones do *you fire?',
 'US State Dept Issues Worldwide Travel Alert',
 'DeepView Computational Tools for Chess Spectatorship',
 'Deposing Tim Cook',
 '2015 in review 1 year after I quit blogging',
 'New Erd?s Paper Solves Egyptian Fraction Problem',
 'Visualizing the Discrete Fourier Transform',
 'Capacitor BigQuerys next-generation columnar storage format',
 "Bitcoin's mining difficulty has increased by 41.9 over the last 30 days",
 'Ask HN Enter market with a well-funded competitor?',
 'Aggregated reviews for iPad Pro 9.7 inch',
 'Analysis of 114 propaganda sources from ISIS Jabhat al-Nusra al-Qaeda [pdf]',
 'Apply HN Hostable Reskinnable Domainable Searchable Forum Software',
 'I was held hostage by Isis They fear our unity more than our airstrikes',
 'Ask HN Do you use any realtime PaaS/framework and in case you so which one?',
 'A malicious module on npm',
 'Ditch Google Forms Try This Free Survey Tool',
 'Introducing Network Containers',
 'Chrome says login.live.com is a Deceptive site',
 'Predicting the Future and Exponential Growth',
 'Electroflight demo electric show aeroplane',
 'Sliding airline seats speed up boarding and departing planes',
 'Limbless master of micrographia featured at the Met',
 'Venezuela to Shut Down for a Week to Cope With Electricity Crisis',
 'A Go check style tool',
 'Apple Watch Scooped Up Over Half the Smartwatch Market in 2015',
 'Pitch your startp Valuate it automatically',
 'Can Wall Street solve the water crisis in the West?',
 'Show HN Webscope Easy way for web developers to communicate with Clients',
 "It's time for the US to use the metric system",
 'Facebook Blames Lack of Available Talent for Diversity Problem',
 'Beyond the Hype 4 Years of Go in Production',
 'The Case for Wooden Skyscrapers',
 'Microsoft patched Windows RT blocks dev Linux boot',
 'New phenomenon breaks inbound TCP policing',
 'PULPino open-source microcontroller based on a 32-bit RISC-V core',
 'Why your Uber app is lying to you about available cars',
 'Facebooks Like Buttons Will Soon Track Your Web Browsing to Target Ads',
 'Grateful Dead Fan Timothy Tyler Has Been Granted Clemency',
 'The Return of the Command Line Interface',
 'ASP.NET OmniSharp server is not running on Ubuntu Mono',
 'Show HN GeoScreenshot Easily test Geo-IP based web pages',
 'Bacon over Lettuce',
 'Ayn Rand Lamp',
 'Scientists identify main component of brain repair after stroke',
 'Munich Gunman Got Weapon from the Darknet [German]',
 "Craig Wright's proof isn't valid because he uses bash background instead of &&",
 'From Python to Lua Why We Switched',
 'Ubuntu 16.04 LTS to Ship Without Python 2',
 'About What is happening with this world?',
 'The Golden Age of Open Protocols',
 'Israeli DDOS Service vDOS responsible for several decades worth of DDoS years',
 'Unaffordable cities this criminal lack of housing is a global scandal',
 'Good UI',
 "CSS Cursor's",
 'Booking.js Availability and Scheduling API',
 'Which MacBook can code 8 hours without charging?',
 'After 60 Years B-52s Still Dominate U.S Fleet',
 'Show HN Run with Mark (Runkeeper only)',
 'Dynamic Swift',
 'The False Promise of DNA Testing',
 "Philip Davies MP 'Political correctness is damaging men'",
 'Ask HN Is there a home Dropbox-style solution  (better explanation inside)',
 'The Glacial Pace of Scientific Publishing',
 'Show HN Send an email from your shell to yourself without pain',
 'Medical researcher discovers integration gets 75 citations',
 'Why Brexit is worse for Europe than Britain',
 'iOS Keychain Privacy Issue',
 'Animatic by Inkboard Animation for everyone animatic.io',
 'Show HN Underline.js is like underscore.js but using modern ES7 syntax',
 'List of Hacker News-style aggregators for specific niches',
 'Show HN Real-Time Stats for an iOS MMORPG Game in a Wordpress Front End',
 "We're Bringing Unsexy Back to Entrepreneurship",
 'Show HN Bild A collection of image processing functions in Go',
 'Show HN Automated coach for programming interviews',
 'Django with websockets and a bolted-on telnet server a hendrix demo',
 'How do I provide value to my startup as a non-technical founder?',
 'Show HN /frink a Slack app for Simpsons gifs',
 'De-anonymizing website visitors via FB timing attacks',
 'How to Satisfy the Worlds Surging Appetite for Meat',
 'Ask HN How would you sell open source software?',
 'Parallax  open source scrolling parallax script for mobile and desktop browsers',
 "Facebook's News Feed",
 "Dear Amazon Prime I don't want to watch the ads for your original series",
 'Amazon ECHO',
 'From Word to Markdown to InDesign Fully Automated Typesetting Using Pandoc',
 'How to use MVC with React',
 'PostgreSQL Linux VS Windows part 2',
 "How an Uncritical Media Helped Trump's Rise",
 'Create a GUI Application Using Qt and Python in Minutes',
 'For the poor in the Ivy League a full ride isnt always what they imagined',
 'Radio FM broadcasting',
 'HN Christmas Colors',
 'Show HN Vector Toy Visualize and manipulate vector field functions',
 'Ask HN Chat-App based on Mail and PGP?',
 'Classic Nintendo Games Are NP-Hard (2012)',
 'Status of legislation on self-driving vehicles across the 50 states',
 'The Pebble smartwatch finally does real fitness tracking',
 'How to Pronounce Hexadecimal',
 'The Mochileros Young Backpackers Risking Their Lives in Cocaine Valley',
 'Deep biomarkers of human aging Application of deep neural networks',
 'Languages Which Almost Became CSS',
 'Drupal Benchmarks',
 "It's time for fancy apartments to offer balconies for drone landings",
 'File indexing and searching for Plan 9 [pdf]',
 'German nuclear plant infected with computer viruses operator says',
 'Computer Specialist Who Deleted Clinton Emails May Have Asked Reddit for Tips',
 'Attack on Kunduz Trauma Centre Afghanistan Initial MSF Internal Review [pdf]',
 'Show HN HTML5 and Canvas demo written in Go',
 'Tactile belt leads the blind and informs wearer of true north',
 'Adobe Photoshop and 1700s Manuscripts A New Approach to Digital Paleography',
 "Google's self-driving car is the victim in a serious crash",
 'Hacked in a public space Thanks HTTPS',
 'An Old-Media Empire Axel Springer Reboots for the Digital Age',
 'Ask HN What you wish you knew before launching your first Wordpress Plugin?',
 'Ask HN How can we get porn sites to support HTTPS?',
 'Pocket Sized Virtual Reality Device',
 'Full Disclosure WinRAR SFX v5.21 Remote Code Execution Vulnerability',
 '$70,000 minimum wage',
 'Email Apps Suck',
 'Ask HN Looking for hacking games.',
 'Ubuntu Team Needs a Cat to Replicate Important Bug',
 'Alyne RegTech Platform for Cyber Security Risk Management and Compliance',
 'How Google Is Remaking Itself as a Machine Learning First Company',
 "Ask HN Are GMail's new features making spam easier?",
 'Ask HN $500k revenue business Shopify vs Custom website?',
 "The Voyeur's Motel",
 "The biggest threat to Silicon Valley isn't what you think it is",
 'What is the best android emulator for mac os?',
 'Ask HN What you learned in 2015?',
 'Coworkers a RabbitMQ microservice framework in Node.js',
 "The FBI 'is manufacturing terrorism cases on a greater scale than ever before",
 'Yahoo lays off 1,700 and is up for sale',
 'The extraordinary case of the Guevedoces',
 'Ask HN Critique my biz idea local.menu the next Airbnb',
 'Ruby on Google AppEngine Goes Beta',
 'How one Silicon Valley engineer negotiated a starting salary from $120k to $250k',
 'Tech Startups Feel an IPO Chill',
 'A brief update',
 'Prevent information leaking in Rails',
 '[Beta Speedtest.net HTML5 Speed Test',
 "How I Solved GCHQ's Xmas Card with Python and Pycosat (Explanation and Source)",
 "Indonesia's palm oil fires emitted more greenhouse gases in a day than the U.S.",
 'Ask HN Resources for learning ASP.NET?',
 'On Nodevember',
 'Ask HN Help Looking to find the x,y,z coordinates of a point in a room',
 'Who the f*ck is this Product Manager at my startup?',
 'Show HN Feeble A React/Redux Architecture',
 'Need to list related videos along with their published date in YouTube?',
 'Cyclists This tiny supercomputer could save your life',
 'Amazon.it starts selling Toyota Aygo online (Italian)',
 'Google Releases the Full Version of Their Search Quality Rating Guidelines',
 'The Heart and Soul of Prototypal OO Concatenative Inheritance',
 'Jony Ive Sighted Driving the Apple Car Through SOMA',
 'Scientists discover molecular difference between male and female brains',
 'A plan to rescue western democracy from the ignorant masses [satire]',
 'Ask HN Apart from HN what other websites you frequent for interesting content?',
 'Numbers Every Programmer Should Know by Year',
 '70,000 OkCupid Users Just Had Their Data Published',
 'How can I advance in my current role?',
 'Transit of the future needs smarter routes not more gadgets',
 'Swastika emoji',
 'Why I killed my standing desk',
 'Calculus Is So Last Century',
 'Google is making better apps for the iPhone than for Android',
 'Lisp C++ Sadness in my heart',
 'MemSQL (YC W11 Raises $36M Series C',
 'New Yorks Sidewalks Are So Packed Pedestrians Are Taking to the Streets',
 'The Talent War Revisited (2011)',
 'On Fungibility Bitcoin Monero and why ZCash is a bad idea',
 "I wrote a script that listens to meetings I'm supposed to be paying attention to",
 'Ask HN How to you browse store sync and backup your family photos?',
 'Ask HN Native way to tell whether a link has been submitted and discussed before?',
 'Dinosaurs Were Declining Way Before That Pesky Asteroid',
 'When Good Waves Go Rogue (2014)',
 'Roll your own video conference tool part 1',
 'Bill Gates Only Government R&D Can Save the Climate Private Sector Is Inept',
 'Man who created own credit card sues bank for not sticking to terms (2013)',
 'A community of and for remote workers',
 'US DoD Using 1970s IBM Series/1 and Floppy Disks for Nuclear Command and Control',
 'Ask HN Do programmers without a degree struggle in Canada (Toronto)?',
 'Ask HN Is asset building as a service (ABaaS a good idea?',
 'What is it like to have never felt an emotion?',
 'Pharo 5.0 Released',
 'How We Hacked the Media and Landed Six-Figure Contracts in Four Days',
 '7-yr-old Google Closure Compiler now in JS',
 'When a dev dies their apps should live on',
 'Kula Ring',
 'Protocol-Oriented MVVM with Natasha the Robot',
 "'Flash Boys IEX stock exchange opens for business",
 'Ask HN Containers and network access?',
 'Ideas for getting started in the Linux kernel',
 'TensorTalk Stay up to date on the latest AI code',
 'Companies would benefit from helping introverts to thrive',
 'GNU on Smartphones (part II)',
 'Reasons why I moved to Switzerland',
 'On the boundaries of GPL enforcement',
 'Startup uses fake ridesharing job ads to trick users into applying for car loans',
 "A small British firm shows that software bugs aren't inevitable (2005)",
 'DockerHub seems down with a 503',
 'Barcode recovery using a priori constraints',
 "Code of Conduct for DigitalOcean's Engineering Team",
 'Apply HN Hire neighborhood students to do your chores while you bloviate online',
 'Show HN Natural Language Time Zone Converter',
 'Researchers achieve speech recognition milestone',
 'The Fake Meat Revolution',
 'Emails Show Unqualified Clinton Foundation Donor Appointed to Intel Board',
 "Disabling npm's progress bar yields a 2x npm install speed",
 'Any Open-Sourced Style Guides?',
 'Why We Hire Great Developers Not Great Mobile Developers',
 'Show HN Unofficial Tinder Client for Apple TV',
 'The Genius of James Brown',
 'Show HN Hire JavaScript  Top JavaScript Talent',
 'India may pull plug on Facebooks bid to offer free Internet service',
 'What Can Happen in the Course of Vulnerability Disclosure',
 'Ask HN What Products/Segments need an open source Alternative?',
 'What Book Has the Most Page-For-Page Wisdom?',
 'Designing for Performance now available for free',
 'Sad Trombone Exoplanet Reality Check',
 'How is NSA breaking so much crypto?',
 "Tech's frightful 5 will dominate the near future",
 'Lost plans for Wright brothers Flying Machine found after 36 years',
 'App Store Subscriptions',
 'Safe Retirement Spending Using TensorFlow',
 'The origins of the Nazis secret horse breeding project',
 'Android AOSP Platform Linux Init.rc Startup Code Trace',
 'Student disqualified for using stackoverflow on stackoverflow',
 'Toyota to Adopt Fords Entertainment Software to Fend Off Google Apple',
 'Newly Discovered Star Has an Almost Pure Oxygen Atmosphere',
 'We Should Not Accept Scientific Results That Have Not Been Repeated',
 'Is the Future of Music a Chip in Your Brain?',
 'In Japan an artificial intelligence has been appointed creative director',
 "What's New in jQuery 3",
 'A 15-Year Series of Campaign Simulators',
 'Background on the "why behind our business model switch',
 'Welsh village adopts multinational tax tactics',
 'Crushing up pain pills and spitting out lives in West Virginia coal country',
 'The DevOps Democracy',
 'If Uber works you might be less happy with your transport options',
 'Who needs an architect?',
 'Microsoft is Working on a New Bot Framework',
 'Microservices Practitioner Summit Livestream Featuring Uber Netflix and Others',
 'Why Pinterest just open-sourced new tools for the Elixir programming language',
 'Show HN Enboard.co',
 "Eclipse Attacks on Bitcoin's Peer-To-Peer Network",
 'What to choose web design or web development?',
 'Does Stress Speed Up Evolution?',
 'Google Improves Image Search with Freebase Identifiers',
 'Frasier on the Electron Microscope',
 "Ask HN Is college even worth it if you're worth your salt as a programmer?",
 'Etsy CTO We Need Software Engineers Not Developers',
 'The College President-To-Adjunct Pay Ratio',
 'Your web  back end stack for 2016?',
 'Facebook Relay An Evil And/Or Incompetent Attack on REST',
 'The Box A Replacement for Files (1999)',
 'Ask HN Look for help order and deliver birthday cake in SF',
 "Ask HN What's the one thing you've always wanted to learn?",
 'New in Linux 4.3 Ambient capabilities',
 'Disposable emails for safe spam free shopping',
 'Perl 6.0 Released',
 'A Brain Dump of What I Worked on for Uncharted 4',
 'Asqway ask questions and get recommendations',
 'Why Dropping the Trans-Pacific Partnership May Be a Bad Idea',
 'Apache Joshua Incubating statistical machine translation decoder 4 phrase-based',
 'Show HN Shapefly|Must Have Free Software Online About Diagram,Flowcharts&Shapes',
 'Atom package that makes you feel like a god',
 'Maxed Out A Closer Look at Coffee Consumption in Finland',
 'Four more carmakers join diesel emissions row',
 'Facebook to Add End-To-End Encrypted Secret Conversations to Messenger App',
 'Imagine yourself starting not finishing',
 "What's Lost When Most People Work from Home",
 'Show HN Make Your Own Custom Map Chart of World Europe United States and More',
 'Ask HN How do you track FOSS releases changelogs?',
 'The Invention of Nature  Alexander von Humboldt the Lost Hero of Science',
 'Baby Bust 2015 had lowest U.S fertility rate ever down 600,000 births',
 'Ask HN Hiring first employee for my startup What documents need to be signed?',
 'Show HN What do you think of my Mongo Logs Utility?',
 'Inky Secure Email Made Easy',
 'Minnesota woman broadcasts police stop and shooting on Facebook Live',
 'Uber for fashion models $20B industry is still very old-fashioned',
 "San Bernardino County tweets it reset attacker iCloud password at FBI's request",
 'Show HN ReadThisThing One fantastic piece of journalism in your inbox daily',
 'In offices of the future sensors may track your every move even in the toilet',
 'Declassified CIA documents detail how to sabotage employers annoy bosses',
 "Why can't I write the word 'tv on the iOS Messages app?",
 'Programming in D A Happy Accident',
 "White students undergo 'deconstructing whiteness program Northwestern Univ",
 'Should Sublime Text goes open source to save itself from falling?',
 'By November Russian hackers could target voting machines',
 'Hunter2 a script-oriented GPG  smartcard-based multiuser password manager',
 'Ask HN teaching basic coding and web design offline solely via iOS devices?',
 'Cover Letters Always Send One',
 'Branwell BrontÃ died standing up leaning against a mantelpiece to prove a point',
 'Ask HN Please validate my business idea',
 'How to remove conflict from conversations when people doubt or challenge you',
 'The Isis papers leaked documents show how Isis is building its state',
 'DNS Basic Concepts (2013)',
 'Microsoft is building its own SIM card for Windows',
 'VW C.E.O Personally Apologized to President Obama in Plea for Mercy',
 'Optimize your content for emotion and persuasion with CopyAwesome.com',
 'What is the most unlimited vacation a person has ever taken?',
 'Swift package manager',
 'RebelBB forum written in Rebol (source code)',
 'Engineers Nine Times More Likely Than Expected to Become Terrorists',
 'Spinning Up a Spark Cluster on Spot Instances Step by Step',

In [ ]:
author = df["author"]

clean_data = []
for i in author:
    clean_data.append(re.sub(r"[^a-zA-Z0-9]", "", i))

clean_data

['ne0phyte',
 'vezycash',
 'hswarna',
 'walterbell',
 'Deinos',
 'shomberj',
 'ahmedbaracat',
 'zt',
 'jimsojim',
 'hitekker',
 'dredmorbius',
 'prostoalex',
 'kfihihc',
 'ingve',
 'rabid oxen',
 'abhishekmaddy',
 'tkfx',
 'jseliger',
 'validly',
 'AliCollins',
 'Tomte',
 'polskibus',
 'Rodi',
 'walterclifford',
 'walterbell',
 'zzzmarcus',
 'mkj',
 'cryptoz',
 'KyleSanderson',
 'sph130',
 'roykolak',
 'GabrielF00',
 'erikvdven',
 'smb06',
 'sheldor',
 'deevus',
 'sethbannon',
 'openmosix',
 'dhotson',
 'sjcsjc',
 'dmitrygr',
 'cdubzzz',
 'LYeo',
 'pmcpinto',
 'jonbaer',
 'h8liu',
 'adamnemecek',
 'Amorymeltzer',
 'zatkin',
 'tomkwok',
 'deafcalculus',
 'nassirkhan',
 'insulanian',
 'ingve',
 'smacktoward',
 'jseliger',
 'fouadmatin',
 'hemapani',
 'fny',
 'porter',
 'vinchuco',
 'rndn',
 'fhoffa',
 'arnauddri',
 'sparkling',
 'adibalcan',
 'crosre',
 'andy ppp',
 'PhasmaFelis',
 'stemuk',
 'gburnett',
 'getvizir',
 'pkcsecurity',
 'whizzkid',
 'urs2102',
 'zeristor',
 'stretchwithme',
 'GuestNetwork',
 'prostoalex',
 'longbai',
 'Jerry2',
 'jo m',
 'elorant',
 'fastbrick',
 'edward',
 'protomyth',
 'neoasterisk',
 'oli5679',
 'type0',
 'RachelF',
 'winterismute',
 'adamsi',
 'EwanToo',
 'WhitneyLand',
 'ghosh',
 'xameeramir',
 'kpsychwave',
 'prtkgpt',
 'jimsojim',
 'Oatseller',
 'p01926',
 'neuropie',
 'chase202',
 ' snydly',
 'imartin2k',
 'worldvoyageur',
 'aarestad',
 'jseliger',
 'jgrodziski',
 'anushbmx',
 'listentojohan',
 'freelancerdever',
 'otoolep',
 'ecesena',
 'mpweiher',
 'sergeant3',
 'lujim',
 'coreyp 1',
 'ingve',
 'ybrs',
 'CarolineW',
 'return0',
 'benzinschleuder',
 'darrenpaul',
 'agp2572',
 'ShinyCyril',
 'ZaneClaes',
 'bevenky',
 'amzans',
 'plicense',
 'jMyles',
 'alex flom',
 'gesteves',
 'aysfrm11',
 'prostoalex',
 'wjh ',
 'gianlucaguarini',
 'jeo1234',
 'thththth',
 'syshackbot',
 'rhythmvs',
 'ludwigvan',
 'based2',
 'citizensixteen',
 'zoodle',
 'wallflower',
 'ejanus',
 'sdiq',
 'dandelany',
 'Databay',
 'iamandoni',
 'sdneirf',
 'akirk',
 'gammarator',
 'desdiv',
 'jonbaer',
 'zackbloom',
 'geerlingguy',
 'cm2187',
 'vezzy fnord',
 'r0muald',
 'heyrhett',
 'andreasley',
 'tidwall',
 'antiffan',
 'benbreen',
 'openmosix',
 'blowski',
 'doener',
 'wp newb',
 'lindx',
 'prbuckley',
 'tomtoise',
 'gricardo99',
 'schneidmaster',
 'dutchbrit',
 'zxv',
 'nr1',
 'elorant',
 'aleem',
 'jimmygatz',
 'cmyr',
 'cryptoz',
 'fimparatta',
 'justplay',
 'tjmehta',
 'ccvannorman',
 'Shofo',
 'BoratObama',
 'andrewfromx',
 'mark l watson',
 'adam klein',
 'pierrealexandre',
 'rbinv',
 'gregmolnar',
 'cquanu',
 'kipi',
 'Thorondor',
 'Catalyst4NaN',
 'Garbage',
 'WheelsAtLarge',
 'raghunayyar',
 ' yesmeck',
 'divyumrastogi',
 'morehuman',
 'lucaspiller',
 'gere',
 'ericelliott',
 'cheerioty',
 'no1ne',
 'sp332',
 'TooSmugToFail',
 'smaili',
 'mhays',
 'payamb',
 'jseliger',
 'sgentle',
 'fluxic',
 'prostoalex',
 'digital55',
 'deepaksurti',
 'ericfrenkiel',
 'baron816',
 'luu',
 'Expez',
 'breadtk',
 'stevesearer',
 'exolymph',
 'curtis',
 'dnetesn',
 'lisper',
 'p4bl0',
 'pelario',
 'luxpir',
 'roymurdock',
 'nikon',
 'tboyd47',
 'andyjohnson0',
 'ch 123',
 'joeyespo',
 'paulddraper',
 'akakievich',
 'Artistry121',
 'astigsen',
 'prostoalex',
 'zaroth',
 'ashitlerferad',
 'tcoder',
 'tomaskazemekas',
 'g1n016399',
 'shawndumas',
 'sciurus',
 'Geekette',
 'cjg',
 'hashfyre',
 'gvb',
 'fweespeech',
 'studentrunnr',
 'hpoydar',
 'gzweig',
 'noondip',
 'ZoeZoeBee',
 'wanda',
 'rahulgulati',
 'astigsen',
 'jshchnz',
 'tintinnabula',
 'eibrahim',
 'giis',
 'edwinjm',
 'bhanu423',
 'miraj',
 'nerdy',
 'cstross',
 'sohkamyung',
 'eric hu',
 'rayascott',
 'dirtyaura',
 'RockyMcNuts',
 'Hooke',
 'srcmap',
 'charlieegan3',
 'ilamont',
 'renatopp',
 'dnetesn',
 'jonbaer',
 'pmcpinto',
 'nfriedly',
 'coloneltcb',
 'Walkman',
 'sofaofthedamned',
 'samclemens',
 'angchappy',
 'yummyfajitas',
 'yusufaytas',
 'nikolay',
 'rschloming',
 'mickael',
 'epagamer',
 'ffwang2',
 'Ingword',
 'dnetesn',
 'PaulHoule',
 'mouzogu',
 'frame perfect',
 'joabj',
 'luu',
 'playing colours',
 'mwcampbell',
 'vezzy fnord',
 'singularitynear',
 'alexgpark',
 'amluto',
 'genesem',
 'hankache',
 'phodo',
 'pratim',
 'JumpCrisscross',
 'based2',
 'zzzhan',
 'jonahugger',
 'pizza',
 'gt565k',
 'envy2',
 'shdc',
 'bootload',
 'whiplashoo',
 'andrewstuart2',
 'Hooke',
 'randomname2',
 'dimasf',
 'data37',
 'tilt',
 ' pius',
 'williswee',
 'randomname2',
 'awwstn',
 'luisramalho',
 'robinwarren',
 'nstj',
 'yarapavan',
 'eplanit',
 'alarbi',
 'DyslexicAtheist',
 'networked',
 'benbreen',
 'mostlystatic',
 'neilellis',
 'springboard',
 'mgdo',
 'callumlocke',
 'rhubarbcustard',
 'lelf',
 'KKKKkkkk1',
 'bickov',
 'justinzollars',
 'famoreira',
 'vmorgulis',
 'richardboegli',
 'ddrum001',
 'rlalwani',
 'ioanarebeca',
 'cameronconaway',
 'andrew eit',
 'genieyclo',
 'ingve',
 'monort',
 'deafcalculus',
 'rcarrigan87',
 'mohitgangrade',
 'sebg',
 'tbirdz',
 'jessaustin',
 'fawce',
 'martincmartin',
 'csl',
 'morninj',
 'Futurebot',
 'cmsefton',
 'lollinghard',
 'cujanovic',
 'userium',
 'jernst',
 'wallflower',
 'vaidik',
 'jamessun',
 'napsterbr',
 'braythwayt',
 'okket',
 'jonaslejon',
 'fabianlindfors',
 'acusticthoughts',
 'doener',
 'daltonlp',
 'kawera',
 'velmu',
 'corvallis',
 'zaytoun',
 'philip1209',
 'gearoidoc',
 'herendin',
 'findher',
 'rory096',
 'MironV',
 'hanniabu',
 't23',
 'max ',
 'jeromeflipo',
 'omribahumi',
 'jgrahamc',
 'janvdberg',
 'anthotny',
 'DrScump',
 'smollett',
 'rayascott',
 'vinnyglennon',
 'skhatri11',
 'kushti',
 'uptown',
 'pentestercrab',
 'jseliger',
 'thecosas',
 'joenathan',
 'hoodoof',
 'jonathanedwards',
 'thenomad',
 'l1n',
 'cryoshon',
 'aryamaan',
 'SCAQTony',
 'callenq',
 'ajiang',
 'soneca',
 'goberoi',
 'dang',
 'ph0rque',
 'syslandscape',
 'l7l',
 'cquanu',
 'nikolay',
 'adamsi',
 'diegoloop',
 'olivercameron',
 'rcpt',
 'Roedou',
 'maverick iceman',
 'vipul4vb',
 'liotier',
 'softvar',
 'adamnemecek',
 'andris9',
 'jaxondu',
 'bootload',
 'nimbus007',
 'johnwheeler',
 'ingve',
 'stedaniels',
 'bootload',
 'Futurebot',
 'snurk',
 'timkham',
 'dineshp2',
 'ambiate',
 'Amorymeltzer',
 'wslh',
 'rl12345',
 'oolong decaf',
 'sohkamyung',
 'szczys',
 'fiatjaf',
 'ithkuil',
 'n3mes1s',
 'akman',
 'robin reala',
 'pritianka',
 'prostoalex',
 'craigcannon',
 'designorant',
 'myroon5',
 'metafunctor',
 'antimora',
 'mobiletelephone',
 'goostavos',
 'danielminkov',
 'flipandtwist',
 'gingerlime',
 'kevinday',
 'randy gilette',
 'shubhamjain',
 'tyh',
 'danielrh',
 'edward',
 'r721',
 'zdw',
 'hharnisch',
 'endswapper',
 'androidlives',
 'throwaway000002',
 'BonoboIO',
 'dwaxe',
 'jsnell',
 'hoodoof',
 'bootload',
 'anon app guy',
 'jakobdabo',
 'chippy',
 'brohee',
 'dwaxe',
 'frutiger',
 'ingve',
 'ajwinn',
 'nickysielicki',
 'alexgpark',
 'cogs',
 'ericcumbee',
 'keywonc',
 'fezz',
 'luu',
 'Turukawa',
 'csomar',
 'sarah adames',
 'tnorgaard',
 'suyash93',
 'jseliger',
 'hoodoof',
 'lispython',
 'rokhayakebe',
 'rchodava',
 'arunc',
 'technologizer',
 'shagunsodhani',
 'mangeletti',
 'garbowza',
 'sabarasaba',
 'pirosb3',
 'azazqadir',
 'jbaviat',
 'rusher81572',
 'Mz',
 'MAshadowlocked',
 'dnetesn',
 'bshanks',
 'MaysonL',
 'throwawaynym',
 'tonyg',
 'hugenerd',
 'j q j',
 'thomasrep',
 'pythonist',
 'hvo',
 'bezierc',
 'nl',
 'arturogarrido',
 'dexterdog',
 'wkoszek',
 'prostoalex',
 'ryan j naughton',
 'desantis',
 'dheavy',
 'gtabx',
 'tux',
 'dustinmoris',
 'uptown',
 'nicoschuele',
 'alexwoodcreates',
 'myroon5',
 'innerspirit',
 'zer0gravity',
 'Amorymeltzer',
 'phildougherty',
 'bluesilver07',
 'donations 2015',
 'chippy',
 'tim sw',
 'tokenadult',
 'steven',
 'Mz',
 'pmcpinto',
 'sjcsjc',
 'DanielRibeiro',
 'stefano',
 'hoodoof',
 'dorseymike',
 'enitihas',
 'DinahDavis',
 'uxhacker',
 'jacquesm',
 'radarsat1',
 'rezist808',
 'prismatic',
 'doctorshady',
 'sjreese',
 'FlopV',
 'donutdan4114',
 'codegeek',
 'hvo',
 'sameernoorani',
 'chrisamanse',
 'replicatorblog',
 'avindroth',
 'jimsojim',
 'enginnr',
 'Jan jw',
 'lelf',
 'anigbrowl',
 'salmonet',
 'lelf',
 'danielam',
 'skewart',
 'cronaldo',
 'noobie',
 'craigcannon',
 'ryan j naughton',
 'twocentstudios',
 'elchief',
 'jessaustin',
 'yaronch',
 'jjuhl',
 'jboydyhacker',
 'chei0aiV',
 'forcer',
 'dberg',
 'e15ctr0n',
 'jonbaer',
 't23',
 'craigkerstiens',
 'ivanzone',
 'trentmc',
 'pm24601',
 'zabramow',
 'alexatkeplar',
 'bootload',
 'jarnix',
 'paukiatwee',
 'devin',
 'networked',
 'shawndumas',
 'rlalwani',
 'andrew wc brown',
 'someear',
 'jamessun',
 'wallflower',
 'ryanmaclean',
 'hampelm',
 'phantom oracle',
 'kristiandupont',
 'varunagrawal',
 'merraksh',
 'andrewmcgivery',
 'martinshen',
 ' Marak ',
 'ryan j naughton',
 'nkurz',
 'throwaway007007',
 'coffeecheque',
 'sebg',
 'appstarter',
 'baus',
 'artf',
 'aburan28',
 'ValQD',
 'cqcn1991',
 'seneka',
 'jcsnv',
 'rhschan',
 'DrScump',
 '2Pacalypse ',
 'lesvizit',
 'phr4ts',
 'Jerry2',
 'meliberki',
 'hownottowrite',
 'dnetesn',
 'ingve',
 'exolymph',
 'thenlater',
 'yungrama',
 'logicalstack',
 'gwintrob',
 'pjmlp',
 'ashitlerferad',
 'kposehn',
 'nanodano',
 'cppdesign',
 'mappu',
 'wb14123',
 'Kovah',
 'kposehn',
 'hackuser',
 '0xmohit',
 'bradley long',
 'emartinelli',
 'aroch',
 'bemmu',
 'alanfranzoni',
 'chippy',
 'hellofunk',
 'Oxydepth',
 'kressaty',
 'geerlingguy',
 'Tomte',
 'coinspotting',
 'workintransit',
 'buchanaf',
 'Deinos',
 'MuEta',
 'ohjeez',
 'rottyguy',
 'tel',
 'benjaminwootton',
 'endswapper',
 'huxingyi',
 'eon01',
 'bane',
 'ryan j naughton',
 'XzetaU8',
 'renafowler',
 'kimh',
 'boulos',
 'feross',
 'fahimulhaq',
 'Sreyanth',
 'coinbaseuser',
 'bpierre',
 'SimplyUseless',
 'ejcx',
 'another',
 'zmanian',
 'have faith',
 'kanso',
 'dsr12',
 'kushti',
 'zeddie',
 'pkaeding',
 'bsilvereagle',
 'natashabaker',
 'johnks',
 'xylon',
 'jodrellblank',
 'aaronhoffman',
 'arouzrokh',
 'scriptdude',
 'skybrian',
 'whattodo123',
 'baptou12',
 'zanewill9',
 'mmariani',
 'ikeboy',
 'jonbaer',
 'willkim',
 'visakanv',
 'throwaway5023',
 'williswee',
 'tallerholler',
 'brianzelip',
 'abustamam',
 'okket',
 'mrry',
 'rwosync',
 'epaga',
 'marketanarchist',
 'ysekand',
 'ceocoder',
 'Gabriel Lewis',
 'benbreen',
 'tanlermin',
 'vanwilson',
 'sarahnadav',
 'kiddz',
 'rrdelaney',
 'theandrewbailey',
 'codegeek',
 'CPAhem',
 'lermontov',
 'apsec112',
 'jonnycombust',
 'okket',
 'vijayr',
 'phwizard',
 'dbob',
 'smacktoward',
 'nkurz',
 'jlturner',
 'adamnemecek',
 'gribbits',
 'hack4supper',
 'danso',
 'alfonsodev',
 'reuven',
 'digital55',
 'woliveirajr',
 'shawndumas',
 'tlrobinson',
 'sanosuke',
 'jcurbo',
 'slideflight',
 'franzunix',
 'ktRolster',
 'roughcoder',
 'compil3r',
 'billowycoat',
 'lorenzhs',
 'peterwwillis',
 'panic',
 'Phithagoras',
 'kungfudoi',
 'mmanfrin',
 'Athas',
 'curtis',
 'anishgodha',
 'rekoros',
 'ggonweb',
 'mstipetic',
 'triplesec',
 'hvo',
 'IamFermat',
 'tallerholler',
 'adambrod',
 'soared',
 'elialbert',
 'Redoubts',
 'guillaumebesse',
 'situationista',
 'liongate2',
 'jewbacca',
 'poushkar',
 'thomanq',
 'vwcx',
 'zackify',
 'T A',
 'dshipper',
 'chintan39',
 'robinhood',
 'hiphipjorge',
 'signa11',
 'redox ',
 'bketelsen',
 'plegros',
 '0xbadb002',
 'hitr',
 'chewymouse',
 'LaSombra',
 'antouank',
 'dominotw',
 'niftylettuce',
 'charlieegan3',
 'UXiomatic',
 'hannes2000',
 'ohjeez',
 'Hooke',
 'sperant',
 'dayon',
 'giis',
 'jcr',
 'sciadvance',
 'voltagex ',
 'ilostmykeys',
 'jellekralt',
 'dtertman',
 'ZeljkoS',
 'wannatouchmyfro',
 'yq',
 'priyatam',
 'adnanh',
 'luu',
 'lvecsey',
 'ltcode',
 'eplanit',
 'kushti',
 'stvnchn',
 '3stripe',
 'vu0tran',
 'eecks',
 'jlos',
 'ingve',
 'relistan',
 'fleitz',
 'sratner',
 'shekhar101',
 'mproud',
 'auganov',
 'vinnyglennon',
 'websec',
 'enraged camel',
 'gvb',
 'wanderer42',
 'chirau',
 'jcr',
 'endswapper',
 'jharohit',
 'armandgw',
 'mirap',
 'thedogeye',
 'tmbsundar',
 'corbet',
 'gregdoesit',
 '6stringmerc',
 'RomanPushkin',
 'k sze',
 'vanilla almond',
 'primroot',
 'w1ntermute',
 'musicnrd',
 'Esperaux',
 'astro ',
 'tdurden',
 'sdogruyol',
 'okket',
 'kawera',
 'aryamaan',
 'dave sullivan',
 'morgenkaffee',
 'michelkarma',
 'stanfordnope',
 'syed123',
 'benanne',
 'eric h',
 'theatraine',
 'iamjeff',
 'qzervaas',
 'danso',
 'codegeek',
 'curtis',
 'hellofunk',
 'hua',
 'smalera',
 'josep2',
 'jimsojim',
 'ingve',
 'lishy',
 'obi1kenobi',
 'aarkay',
 'sharemywin',
 'lgse',
 'Mattasher',
 'upen',
 'hagbarddenstore',
 'mpgirro',
 'walterbell',
 'rmason',
 'tilt',
 'compil3r',
 'iskin',
 'forrestbrazeal',
 'lisper',
 'ctex',
 'kbart',
 'ffggvv',
 'samsolomon',
 'uptown',
 'dedalus',
 'russ b ukg',
 'jotux',
 'the bong one',
 'alexellisuk',
 'benbreen',
 'zxcvbnmmnbvcxz',
 'indatawetrust',
 'petethomas',
 'danial',
 'poppup',
 'c0nrad',
 'trueduke',
 'nols',
 'based2',
 'bomanbot',
 'virtualwhys',
 'dartf',
 'hackerews',
 'nadavs',
 'SonicSoul',
 'wslh',
 'calcsam',
 'magic man',
 'mablae',
 'dnetesn',
 'markmassie',
 'daveloyall',
 'Tekmasta',
 'davidgerard',
 'prostoalex',
 'snake case',
 'zoran119',
 'xd1936',
 'razer6',
 'cpeterso',
 'alishamiudo',
 'angersock',
 'alexkehr',
 'philippnagel',
 'elliotchance',
 'crad',
 'apsec112',
 'xoher',
 'unfortunateface',
 'ekianjo',
 'yarapavan',
 'edward',
 'tmbsundar',
 'roccogen',
 ...]