In [ ]:
import sqlite3 as sql
import pandas as pd

conn = sql.connect('factbook.db')
conn

query = ""
def sql_query_fun(query):
    return pd.read_sql_query(query, conn)
    
query = "SELECT * FROM sqlite_master"
sql_query_fun(query)

,type,name,tbl_name,rootpage,sql
0,table,sqlite_sequence,sqlite_sequence,3,"CREATE TABLE sqlite_sequence(name,seq)"
1,table,facts,facts,47,"CREATE TABLE ""facts"" (""id"" INTEGER PRIMARY KEY..."
2,table,cities,cities,2,CREATE TABLE cities (\n id integer prim...

In [6]:
# check table 
query = "SELECT name FROM sqlite_master WHERE type='table'"
sql_query_fun(query)

              name
0  sqlite_sequence
1            facts
2           cities

In [10]:
# check table info
query = "PRAGMA table_info(facts)"
sql_query_fun(query)

    cid               name          type  notnull dflt_value  pk
0     0                 id       INTEGER        1       None   1
1     1               code  varchar(255)        1       None   0
2     2               name  varchar(255)        1       None   0
3     3               area       INTEGER        0       None   0
4     4          area_land       INTEGER        0       None   0
5     5         area_water       INTEGER        0       None   0
6     6         population       INTEGER        0       None   0
7     7  population_growth         float        0       None   0
8     8         birth_rate         float        0       None   0
9     9         death_rate         float        0       None   0
10   10     migration_rate         float        0       None   0

In [ ]:
query = "PRAGMA table_info(cities)"
sql_query_fun(query)

   cid        name     type  notnull dflt_value  pk
0    0          id  INTEGER        0       None   1
1    1        name     TEXT        0       None   0
2    2  population  INTEGER        0       None   0
3    3     capital     bool        0       None   0
4    4    facts_id     TEXT        0       None   0

In [15]:
query = "SELECT * FROM facts "
sql_query_fun(query)

,id,code,name,area,area_land,area_water,population,population_growth,birth_rate,death_rate,migration_rate
0,1,af,Afghanistan,652230.0,652230.0,0.0,3.256434e+07,2.32,38.57,13.89,1.51
1,2,al,Albania,28748.0,27398.0,1350.0,3.029278e+06,0.30,12.92,6.58,3.30
2,3,ag,Algeria,2381741.0,2381741.0,0.0,3.954217e+07,1.84,23.67,4.31,0.92
3,4,an,Andorra,468.0,468.0,0.0,8.558000e+04,0.12,8.13,6.96,0.00
4,5,ao,Angola,1246700.0,1246700.0,0.0,1.962535e+07,2.78,38.78,11.49,0.46
...,...,...,...,...,...,...,...,...,...,...,...
256,257,zh,Atlantic Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,258,xo,Indian Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,259,zn,Pacific Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259,260,oo,Southern Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,261,xx,World,NaN,NaN,NaN,7.256490e+09,1.08,18.60,7.80,NaN

In [16]:
query = "SELECT * FROM cities"
sql_query_fun(query)

      id          name  population  capital facts_id
0      1    Oranjestad       37000        1      216
1      2  Saint John'S       27000        1        6
2      3     Abu Dhabi      942000        1      184
3      4         Dubai     1978000        0      184
4      5       Sharjah      983000        0      184
..   ...           ...         ...      ...      ...
392  393       Mbabane       66000        1      167
393  394         Sanaa     2419000        1      193
394  395          Aden      784000        0      193
395  396        Lusaka     1802000        1      194
396  397        Harare     1542000        1      195

[397 rows x 5 columns]

In [ ]:
query = "SELECT f.name, c.name AS city_name FROM facts f INNER JOIN cities c ON f.id = c.facts_id WHERE f.name = 'Pakistan'"
sql_query_fun(query)