In [ ]:
from asyncio import QueueEmpty
import sqlite3 as sql
import pandas as pd
import numpy as np

conn = sql.connect('database.sqlite')
conn

query = ""
def sql_query_fun(query):
    return pd.read_sql_query(query, conn)

sql_query_fun("select * from sqlite_master")

,type,name,tbl_name,rootpage,sql
0,table,Salaries,Salaries,2,CREATE TABLE Salaries (\n Id INTEGER PRIMAR...
1,index,salaries_year_idx,Salaries,16566,CREATE INDEX salaries_year_idx ON Salaries (Year)

In [12]:
# Job titles with more than 5 employees and average TotalPay greater than 100k
query = "SELECT JobTitle, COUNT(*) AS EmployeeCount, AVG(TotalPay) AS Average_TotalPay FROM salaries GROUP BY JobTitle HAVING COUNT(*) > 5 AND AVG(TotalPay) > 100000"
sql_query_fun(query)

                           JobTitle  EmployeeCount  Average_TotalPay
0           ADMINISTRATIVE ENGINEER             10     127961.430000
1          AIRPORT ECONOMIC PLANNER             13     108264.821538
2               AIRPORT ELECTRICIAN             17     108707.828235
3                       ANESTHETIST             25     112265.260400
4        ASSISTANT CHIEF ATTORNEY I             23     174307.873913
..                              ...            ...               ...
379      Water & Power Maint Sprv 1              9     105269.957778
380        Water Conservation Admin             12     114135.847500
381        Water Operations Analyst             35     101959.531429
382              Watershed Forester              6     100079.838333
383  Wire Rope Cable Maint Mechanic             30     112211.526000

[384 rows x 3 columns]

In [ ]:
# Employees with average BasePay greater than 50k by JobTitle

query =  "SELECT Year, COUNT(*) AS Employee_Count FROM salaries GROUP BY Year HAVING COUNT(*) > 10" 
sql_query_fun(query)

   Year  Employee_Count
0  2011           36159
1  2012           36766
2  2013           37606
3  2014           38123

In [ ]:
# Employees with average BasePay greater than 50k by JobTitle

query = "SELECT JobTitle, AVG(BasePay) AS 'Average BasePay' FROM salaries GROUP BY JobTitle HAVING AVG(BasePay) > 50000"
sql_query_fun(query)

                                    JobTitle  employee_count  avg_base_pay
0                            Chief of Police               3     309767.68
1                     Chief, Fire Department               3     304232.34
2                 Gen Mgr, Public Trnsp Dept               3     297769.41
3     CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)               1     285262.00
4               Dep Dir for Investments, Ret               2     276153.77
...                                      ...             ...           ...
1721               LICENSED VOCATIONAL NURSE             194      50205.27
1722                       LABORATORY HELPER               1      50142.40
1723                        Asphalt Finisher              36      50103.42
1724            DISEASE CONTROL INVESTIGATOR               9      50072.41
1725           Victim/Witness Investigator 1              61      50004.68

[1726 rows x 3 columns]